### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by hildjj** [hildjj/set-game#1]
I noticed that @geophree just forked this repo, which was never actually working.  The least I could do is update the dependencies and make the tests run again.

**Comment by geophree** [comment]
I was mostly so I had a copy of the cards (they look really nice!). Who knows if I'll ever get around to doing anything with it. :laughing:

**Comment by hildjj** [comment]
Well, there's at least ugly HTML support for you now, so you can see the SVG in action.  
`node index.js --html`
